Repository whatever-x/backend, pull requests merged in 2025-07, with the labels that each got.

#194 [Feat] update user setting 유닛 테스트 추가
  build.gradle
  src/main/kotlin/com/whatever/domain/user/service/UserService.kt
  src/test/kotlin/com/whatever/domain/user/service/UserServiceTest.kt
  src/test/kotlin/com/whatever/domain/user/service/UserServiceUnitTest.kt
Labels: ⭐ Test

#195 [Chore] mockk 추가
  build.gradle
Labels: ➕Enhancement

#201 [Refactor] Mockito 사용 테스트코드를 Mockito-Kotlin 스타일로 개선
  src/test/kotlin/com/whatever/WhateverBackendApplicationTests.kt
  src/test/kotlin/com/whatever/domain/auth/service/provider/KakaoUserProviderTest.kt
Labels: 🔧Fix

#204 [Test] getuserinfo 테스트 작성
  src/test/kotlin/com/whatever/domain/user/service/UserServiceUnitTest.kt
Labels: ⭐ Test

#206 [Test] updateProfile 테스트 코드 작성 입니다
  src/main/kotlin/com/whatever/domain/user/service/UserService.kt
  src/test/kotlin/com/whatever/domain/user/service/UserServiceUnitTest.kt
Labels: ⭐ Test

#209 [Test] createProfile 테스트 작성
  src/test/kotlin/com/whatever/domain/user/service/UserServiceUnitTest.kt
Labels: ⭐ Test

#222 [Test] balance game 테스트 코드 추가
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/balancegame/service/BalanceGameService.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/balancegame/service/BalanceGameServiceTest.kt
Labels: ⭐ Test

#228 [Feat] 일정 담당자 assignee 추가
  caramel-api/src/main/kotlin/com/whatever/caramel/api/auth/dto/SignInResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/controller/dto/response/CalendarEventInfoResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/CreateScheduleRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/UpdateScheduleRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/CreateContentRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/UpdateContentRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentInfoResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentSummaryResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/TagDto.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/tag/controller/dto/request/TagIdDto.kt
  caramel-api/src/test/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/ScheduleControllerTest.kt
  caramel-api/src/test/kotlin/com/whatever/caramel/api/content/controller/ContentControllerTest.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/calendarevent/service/ScheduleEventService.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/calendarevent/vo/CreateScheduleVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/calendarevent/vo/ScheduleDetailVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/calendarevent/vo/UpdateScheduleVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/model/Content.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/service/ContentService.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/service/MemoCreator.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/service/ScheduleCreator.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/vo/ContentAssignee.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/vo/ContentResponseVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/vo/ContentVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/vo/CreateContentRequestVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/content/vo/UpdateContentRequestVo.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/calendarevent/scheduleevent/service/ScheduleEventCreateServiceTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/calendarevent/scheduleevent/service/ScheduleEventServiceOptimisticLockTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/calendarevent/scheduleevent/service/ScheduleEventServiceTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/content/service/ContentServiceRetryableTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/content/service/ContentServiceTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/content/service/ContentServiceUnitTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/content/service/MemoToScheduleConvertTest.kt
Labels: ➕Enhancement

#230 [Feat] 컨텐츠 담당자 응답 및 요청에 description 변경
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/controller/dto/response/CalendarEventInfoResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/CreateScheduleRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/dto/UpdateScheduleRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/CreateContentRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/request/UpdateContentRequest.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentInfoResponse.kt
Labels: 📚Docs

#232 [Bug] ContentInfoResponse 에서 tagList 응답 잘못 내려가는 것 수정
  caramel-api/src/main/kotlin/com/whatever/caramel/api/content/controller/dto/response/ContentInfoResponse.kt
Labels: 🐞Bug

#234 [Fix] /v1/calendar/schedules 에서 응답 모듈화 전으로 롤백
  caramel-api/src/main/kotlin/com/whatever/caramel/api/calendarevent/scheduleevent/controller/ScheduleController.kt
Labels: 🐞Bug
