Repository whatever-x/backend, pull requests merged in 2025-08, with the labels that each got.

#254 [Fix] JdbcTransactionManager로 덮어 씌우지는 것 수정
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/config/FcmBatchConfig.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/config/JpaConfig.kt
Labels: 🐞Bug

#256 [Fix] BatchTxManager와 JpaTxManager 분리
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/config/FcmBatchConfig.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/config/JpaConfig.kt
Labels: 🔧Fix

#262 [Feat] 배치를 통해 FCM 전송 및 테이블 최신화
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/AnniversaryBatchScheduler.kt
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/config/BatchConfig.kt
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/config/FcmBatchConfig.kt
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/config/ScheduleNotificationRemoveBatchConfig.kt
  caramel-batch/src/main/kotlin/com/whatever/caramel/batch/entity/BatchFcmNotification.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/config/JpaConfig.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/notification/repository/ScheduledNotificationRepository.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/notification/service/ScheduledNotificationService.kt
Labels: ➕Enhancement

#260 [Feat] 강제 업데이트를 위한 클라이언트 버전 체크 API 추가
  caramel-api/src/main/kotlin/com/whatever/caramel/api/clientversion/controller/ClientVersionController.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/api/clientversion/controller/dto/GetUpdatePolicyResponse.kt
  caramel-api/src/main/kotlin/com/whatever/caramel/config/SecurityConfig.kt
  caramel-api/src/main/resources/application.yaml
  caramel-common/src/main/kotlin/com/whatever/caramel/common/global/constants/CaramelHttpHeader.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/config/CacheConfig.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/auth/service/AuthService.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/model/ClientVersion.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/model/OsType.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/model/OsVersionPolicy.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/repository/ClientVersionRepository.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/repository/OsVersionPolicyRepository.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionCacheService.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionService.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/vo/ClientVersionVo.kt
  caramel-domain/src/main/kotlin/com/whatever/caramel/domain/clientversion/vo/VersionPolicyVo.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/auth/service/AuthServiceTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionCacheServiceTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionCacheServiceUnitTest.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionServiceTestSupport.kt
  caramel-domain/src/test/kotlin/com/whatever/caramel/domain/clientversion/service/ClientVersionServiceUnitTest.kt
  caramel-infrastructure/src/main/kotlin/com/whatever/caramel/infrastructure/client/AppleFeignClient.kt
  caramel-infrastructure/src/main/kotlin/com/whatever/caramel/infrastructure/client/KakaoFeignClient.kt
Labels: ➕Enhancement
